plugins {
    id 'org.relativitymc.neo-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
    mavenCentral()
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        url = "https://jitpack.io/"
    }
    maven {
        url "https://maven.su5ed.dev/releases"
    }
    maven {
        name 'Xander Maven'
        url 'https://maven.isxander.dev/releases'
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

sourceSets {
    sereneSeasons {
        java {
            srcDir 'src/sereneSeasons/java'
        }
        resources {
            srcDir 'src/sereneSeasons/resources'
        }

        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
        compileClasspath += main.output
        runtimeClasspath += main.output
    }
}

loom {
    mods {
        "thermoo_patches_serene_seasons_patch" {
            sourceSet sourceSets.sereneSeasons
        }
        "thermoo_patches" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.21.1:2024.11.17@zip")
    }
    neoForge "net.neoforged:neoforge:${project.loader_version}"

    include(implementation("dev.yumi.mc.core:yumi-mc-foundation:${project.yumi_mc_version}") {
        attributes {
            attribute(Attribute.of("net.minecraft.mappings", String), "mojmap")
        }
    })

    api "com.github.thedeathlycow:thermoo:v${project.thermoo_version}"
    api "dev.isxander:yet-another-config-lib:${project.yacl_version}"

    sereneSeasonsCompileOnly("maven.modrinth:serene-seasons:${project.serene_seasons_version}")
}

processResources {
    var expandProps = [
            "version": project.mod_version,
            "loader_version": project.loader_version,
            "thermoo_version": project.thermoo_version,
            "yacl_version": project.yacl_version,
    ]

    inputs.properties(expandProps)

    filesMatching("META-INF/neoforge.mods.toml") {
        expand expandProps
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    def projectName = project.name
    inputs.property "projectName", projectName

    from("LICENSE") {
        rename { "${it}_$projectName" }
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
