plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT'
    id 'maven-publish'
    id "me.modmuss50.mod-publish-plugin" version "2.0.0-beta.1"
}

var mod_version = project.mod_version
version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

allprojects {
    apply plugin: 'net.fabricmc.fabric-loom'

    repositories {
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
        maven { url "https://jitpack.io/" }
        maven {
            name = "Ladysnake Mod Releases"
            url = 'https://maven.ladysnake.org/releases'
        }
        maven {
            name = "Ladysnake Mod Snapshots"
            url = 'https://maven.ladysnake.org/snapshots'
        }
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.terraformersmc.com/" }
        maven { url "https://maven.resourcefulbees.com/repository/maven-public/" }
        maven {
            url = 'https://maven.cafeteria.dev'
            content {
                includeGroup 'net.adriantodt.fabricmc'
            }
        }
        maven {
            url "https://maven.jamieswhiteshirt.com/libs-release"
            content {
                includeGroup "com.jamieswhiteshirt"
            }
        }
        maven {
            url "https://masa.dy.fi/maven"
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }
    }

    dependencies {
        // To change the versions see the gradle.properties file
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        implementation "net.fabricmc:fabric-loader:${project.loader_version}"

        // required dependencies
        implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
        implementation "maven.modrinth:thermoo:${project.thermoo_version}"
        implementation "com.terraformersmc:modmenu:${project.mod_menu_version}"
        api("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") {
            exclude(group: "net.fabricmc.fabric-api")
        }
    }

    loom {
        splitEnvironmentSourceSets()
    }

    tasks.withType(ProcessResources).configureEach {
        inputs.property "version", project.findProperty('mod_version')
        inputs.property "java_version", project.findProperty('java_version')
        inputs.property "minecraft_versions", project.findProperty('minecraft_versions')
        inputs.property "loader_version", project.findProperty('loader_version')
        inputs.property "fabric_version", project.findProperty('fabric_version')
        inputs.property "thermoo_version", project.findProperty('thermoo_version')
        inputs.property "cloth_config_version", project.findProperty('cloth_config_version')
        inputs.property "mod_menu_version", project.findProperty('mod_menu_version')

        filesMatching("fabric.mod.json") {
            expand(
                    "version": project.findProperty('mod_version'),
                    "java_version": project.findProperty('java_version'),
                    "minecraft_versions": project.findProperty('minecraft_versions'),
                    "loader_version": project.findProperty('loader_version'),
                    "fabric_version": project.findProperty('fabric_version'),
                    "thermoo_version": project.findProperty('thermoo_version'),
                    "cloth_config_version": project.findProperty('cloth_config_version'),
                    "mod_menu_version": project.findProperty('mod_menu_version'),
            )
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 25
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }
}

dependencies {
    api project(path: ":thermoo-patches-base")
//    api project(path: ":thermoo-patches-fabric-seasons-patch")
//    api project(path: ":thermoo-patches-simple-seasons-patch")
    api project(path: ":thermoo-patches-serene-seasons-patch")
//    api project(path: ":thermoo-patches-immersive-weathering-patch")
    api project(path: ":thermoo-patches-friendsandfoes-patch")
//    api project(path: ":thermoo-patches-colorfulhearts-patch")
    api project(path: ":thermoo-patches-overflowing-bars-patch")
//    api project(path: ":thermoo-patches-armorpointspp-patch")
//    api project(path: ":thermoo-patches-origins-patch")
//    api project(path: ":thermoo-patches-stellaris-patch")

    include(project(path: ":thermoo-patches-base"))
//    include(project(path: ":thermoo-patches-fabric-seasons-patch"))
//    include(project(path: ":thermoo-patches-simple-seasons-patch"))
    include(project(path: ":thermoo-patches-serene-seasons-patch"))
//    include(project(path: ":thermoo-patches-immersive-weathering-patch"))
    include(project(path: ":thermoo-patches-friendsandfoes-patch"))
//    include(project(path: ":thermoo-patches-colorfulhearts-patch"))
    include(project(path: ":thermoo-patches-overflowing-bars-patch"))
//    include(project(path: ":thermoo-patches-armorpointspp-patch"))
//    include(project(path: ":thermoo-patches-origins-patch"))
//    include(project(path: ":thermoo-patches-stellaris-patch"))
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

publishMods {
    changelog = file("changelogs/${mod_version}.md").text
    type = STABLE
    displayName = "Thermoo Patches ${mod_version}"

    file = jar.archiveFile
    modLoaders.add("fabric")
    modLoaders.add("quilt")

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = "1012677"
        minecraftVersions.addAll("26.1", "26.1.1", "26.1.2")

        javaVersions.add(JavaVersion.VERSION_25)

        clientRequired = true
        serverRequired = true

        requires("fabric-api", "thermoo", "cloth-config")
        optional(
                "serene-seasons",
                "friends-and-foes",
                "overflowing-bars",
        )
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "TYRF9nUy"
        minecraftVersions.addAll("26.1", "26.1.1", "26.1.2")

        requires("fabric-api", "thermoo", "cloth-config")

        optional(
                "serene-seasons",
                "friends-and-foes",
                "overflowing-bars",
        )
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}