# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

java_version=21

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9

# Mod Properties
mod_version=3.7.1
maven_group=com.github.thedeathlycow.thermoo.patches
archives_base_name=thermoo-patches

minecraft_versions=>=1.21 <=1.21.1

# Dependencies
fabric_version=0.110.0+1.21.1
thermoo_version=4.5
cloth_config_version=15.0.140
mod_menu_version=11.0.3

## Java Integrations ##

# 1.21.1 integrations
# colorful hearts: [Fabric] 1.21.1-v10.3.8
colorfulhearts_version=r2mnc8w2
# serene seasons: 10.1.0.1 for Fabric 1.21.1
serene_seasons_version=UqA7miTT
fabric_seasons_version=2.4.2-BETA+1.21
overflowingbars_version=v21.1.1-1.21.1-Fabric
simple_seasons_version=1.1.0+mc1.21-1.21.1
friends_and_foes_version=fabric-mc1.21.1-4.0.1
# required for Friends and Foes, 3.0.12
resourceful_lib_version=Hf91FuVF
# Stellaris 1.3.7
stellaris_version=dJQAyPdN
origins_version=1.13.0-alpha.12+mc.1.21.1

# rest are not updated yet, lol

# 1.20.2 only
libhud_version=1.0.0-beta6
# 1.20.4, but requires libhud
armorpointspp_version=fabric-1.20-3.1.2

# 1.20.1 only
immersive_weathering_version=1.20.1-2.0.1
