pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

include 'thermoo-patches-base'
include 'thermoo-patches-fabric-seasons-patch'
include 'thermoo-patches-simple-seasons-patch'
include 'thermoo-patches-serene-seasons-patch'
include 'thermoo-patches-immersive-weathering-patch'