# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml"

loaderVersion="[1,)"
license="LGPL-3.0"

issueTrackerURL="https://www.github.com/TheDeathlyCow/thermoo-patches/issues"

[[mods]]
modId="${mod_id}_overflowing_bars_patch"

version="${version}"

displayName="Thermoo Patches NeoForge: Overflowing Bars Patch"

displayURL="https://www.thedeathlycow.com/thermoo-patches"

logoFile="assets/thermoo-patches-overflowing-bars-patch/icon.png"

#credits="" #optional

authors="TheDeathlyCow"

description='''Overflowing Bars integration patch for Thermoo'''

[modproperties.${mod_id}_overflowing_bars_patch."yumi:entrypoints"]
"yumi:client_init" = "com.github.thedeathlycow.thermoo.patches.neoforge.overflowing.bars.OverflowingBarsPatch"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}_overflowing_bars_patch]]
modId="neoforge"
type="required"
versionRange="[${loader_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}_overflowing_bars_patch]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}_overflowing_bars_patch]]
modId="yet_another_config_lib_v3"
type="required"
versionRange="[${yacl_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}_overflowing_bars_patch]]
modId="thermoo"
type="required"
versionRange="[${thermoo_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}_overflowing_bars_patch]]
modId="${mod_id}"
type="required"
versionRange="[${version},)"
ordering="AFTER"
side="BOTH"