
version = rootProject.mod_version

base {
    archivesName = "thermoo-patches-immersive-weathering-patch"
}

dependencies {
    api project(path: ':thermoo-patches-base', configuration: 'namedElements')

    modCompileOnly "maven.modrinth:immersive-weathering:${project.immersive_weathering_version}"
}