
version = rootProject.mod_version

base {
    archivesName = "thermoo-patches-armorpointspp-patch"
}

dependencies {
    api project(path: ':thermoo-patches-base', configuration: 'namedElements')

    modCompileOnly "maven.modrinth:libhud:${project.libhud_version}"
    modCompileOnly "maven.modrinth:armorpoints:${project.armorpointspp_version}"
}