
version = rootProject.mod_version

base {
    archivesName = "thermoo-patches-colorfulhearts-patch"
}

dependencies {
    api project(path: ':thermoo-patches-base', configuration: 'namedElements')
    include(project(path: ':thermoo-patches-base'))

    modCompileOnly "maven.modrinth:colorful-hearts:${project.colorfulhearts_version}"
}