
version = rootProject.mod_version

base {
    archivesName = "thermoo-patches-friendsandfoes-patch"
}

dependencies {
    api project(path: ':thermoo-patches-base')

    compileOnly "maven.modrinth:resourceful-lib:${project.resourceful_lib_version}"
    compileOnly "maven.modrinth:friends-and-foes:${project.friends_and_foes_version}"
}